module.exports = {
  USER: "public/avatar",
  USER_IMAGE: "avatar",
  USER_THUMB: "public/avatar/thumb",
  USER_IMAGE_PATH: "userImage",
  DOCUMENT: "audit-document/sla",
  AUDIT_DOCUMENT: "audit-document/",
  DOWNLOAD_DOCUMENT: "download-document/",
  COMPANY_DOCUMENT: "company_document/",
  REPORT_DOCUMENT: "report_document/",
  DOCUMENT_PATH: "public/audit-document/sla",
  DOCUMENT_IMAGE_PATH: "document",
  INVOICE_IMAGE_PATH: "invoice",
  USER_HEIGHT: 500,
  USER_WIDTH: 500,
  USER_DEFULTY_IMAGE: "static/user.svg",
  MAX_IMAGE_SIZE: 1,
  NodeMailertansport: {
    host: "smtp.gmail.com",
    port: 587,
    secure: false, // true for 465, false for other ports
    auth: {
      user: "anil.octal@gmail.com", // generated ethereal user
      pass: "octal@123", // generated ethereal password
    },
  },
  INVOICE_PATH: "public/invoices",
  AUDIT_STATUS: [
    "CREATED",
    "SLASIGNED",
    "PROGRESS",
    "COMPLETED",
    "DOCUMENT",
    "ASSIGNED",
    "REPORT_UPLOAD",
    "REPORT_REJECT",
    "AU_GOVERNMENT",
    "INVOICE_PAID",
    "KEP_UPDATE",
    "REQUEST_AUDIT",
    "AUDIT_DATE_BOOK",
    "ACCEPT_REPORT",
    "REPORT_REJECT_STAGE",
    "REQUEST_STAGE",
    "INVOICE_PAID_STAGE",
    "STAGE_CONFORM",
    "PROGRESS_STAGE",
    "REPORT_UPLOAD_STAGE",
    "SEND_PEER",
    "REPORT_REVIEW",
    "SEND_REPORT_COMPANY",
    "STAGE_COMPLETED",
    "ACCEPT_REPORT_STAGE",
  ],
  AUDIT_TYPE: ["VERIFICATION", "CERTIFICATION"],
  DOCUMENT_SING_ARRAY: ["SELF", "DOCUSIGN", "NO"],
  AUDIT_STATUS_ARRAY: {
    CREATED: "Audit Created",
    SLASIGNED: "Agreement Signed",
    DOCUMENT: "Documents Uploaded",
    PROGRESS: "Audit Commenced",
    REPORT_UPLOAD: "Report Uploaded",
    REPORT_REJECT: "Report Rejected",
    REPORT_REJECT_STAGE: "Report Rejected",
    ACCEPT_REPORT: "Report finalized by provider",
    COMPLETED: "Completed",
    AU_GOVERNMENT: "Report submitted to NDIA",
    INVOICE_PAID: "Invoice Paid",
    KEP_UPDATE: "KP Updated",
    REQUEST_AUDIT: "Request Audit Date",
    AUDIT_DATE_BOOK: "Audit date booked in",
    REQUEST_STAGE: "Request Stage 2 Audit Date",
    INVOICE_PAID_STAGE: "Invoice Paid Stage 2 Audit",
    STAGE_CONFORM: "Audit date booked in",
    PROGRESS_STAGE: "Audit Stage 2 Commenced",
    REPORT_UPLOAD_STAGE: "Report Uploaded",
    SEND_PEER: "Audit Commenced",
    REPORT_REVIEW: "Audit Commenced",
    SEND_REPORT_COMPANY: "Audit Commenced",
  },
  AUDIT_STATUS_ARRAY_ADMIN: {
    CREATED: "Audit Created",
    SLASIGNED: "Agreement Signed",
    DOCUMENT: "Documents Uploaded",
    PROGRESS: "Audit Commenced",
    REPORT_UPLOAD: "Report Uploaded",
    REPORT_REJECT: "Report Rejected",
    REPORT_REJECT_STAGE: "Report Rejected",
    ACCEPT_REPORT: "Report finalized by provider",
    COMPLETED: "Completed",
    AU_GOVERNMENT: "Report submitted to NDIA",
    INVOICE_PAID: "Invoice Paid",
    KEP_UPDATE: "KP Updated",
    REQUEST_AUDIT: "Request Audit Date",
    AUDIT_DATE_BOOK: "Audit date booked in",
    REQUEST_STAGE: "Request Stage 2 Audit Date",
    INVOICE_PAID_STAGE: "Invoice Paid Stage 2 Audit",
    STAGE_CONFORM: "Audit date booked in",
    PROGRESS_STAGE: "Audit Stage 2 Commenced",
    REPORT_UPLOAD_STAGE: "Report Uploaded",
    SEND_PEER: "Sent report peer auditor",
    REPORT_REVIEW: "Report reviewed by peer auditor",
    SEND_REPORT_COMPANY: "Sent report to company",
  },
  AUDIT_STATUS_ARRAY_AUDITOR: {
    CREATED: "Audit Created",
    SLASIGNED: "Agreement Signed",
    DOCUMENT: "Documents Uploaded",
    PROGRESS: "Audit Commenced",
    REPORT_UPLOAD: "Report Uploaded",
    REPORT_REJECT: "Report Rejected",
    REPORT_REJECT_STAGE: "Report Rejected",
    ACCEPT_REPORT: "Report finalized by company",
    COMPLETED: "Completed",
    AU_GOVERNMENT: "Report submitted to NDIA",
    INVOICE_PAID: "Invoice Paid",
    KEP_UPDATE: "KP Updated",
    REQUEST_AUDIT: "Request Audit Date",
    AUDIT_DATE_BOOK: "Audit date booked in",
    REQUEST_STAGE: "Request Stage 2 Audit Date",
    INVOICE_PAID_STAGE: "Invoice Paid Stage 2 Audit",
    STAGE_CONFORM: "Audit date booked in",
    PROGRESS_STAGE: "Audit Stage 2 Commenced",
    REPORT_UPLOAD_STAGE: "Report Uploaded",
    SEND_PEER: "Sent report peer auditor",
    REPORT_REVIEW: "Report reviewed by peer auditor",
    SEND_REPORT_COMPANY: "Sent report to company",
  },
  AUDIT_NEXT_STEP: {
    CREATED: "Agreement Sign",
    SLASIGNED: "Invoice Paid",
    INVOICE_PAID: "KP Updated",
    KEP_UPDATE: "Document Upload Complete",
    DOCUMENT: "Request Audit Date",
    REQUEST_AUDIT: "Audit date booked in",
    AUDIT_DATE_BOOK: "Audit commenced",
    PROGRESS: "Report finalized by provider",
    REPORT_UPLOAD: "Waiting for report",
    REPORT_REJECT: "Waiting for report",
    ACCEPT_REPORT: "Report submitted to NDIA",
    COMPLETED: "Report submitted to NDIA",
  },
  AUDIT_NEXT_STEP_CERTIFICATION: {
    CREATED: "Agreement Sign",
    SLASIGNED: "Invoice Paid",
    INVOICE_PAID: "Document Upload Complete",
    DOCUMENT: "Request Stage 1 Audit Date",
    REQUEST_AUDIT: "Audit date booked in",
    AUDIT_DATE_BOOK: "Stage 1 Completed",
    PROGRESS: "Report Accept/Reject",
    REPORT_UPLOAD: "Report Accept/Reject",
    REPORT_REJECT: "Waiting for report",
    ACCEPT_REPORT: "Request Stage 2 Audit Date",
    REQUEST_STAGE: "Audit date booked in",
    STAGE_CONFORM: "Stage 2 Completed",
    PROGRESS_STAGE: "Stage 2 Completed",
    REPORT_UPLOAD_STAGE: "Make final payment",
    INVOICE_PAID_STAGE: "Waiting for report",
    SEND_PEER: "Waiting for report",
    REPORT_REVIEW: "Waiting for report",
    SEND_REPORT_COMPANY: "Report Accept/Reject",
    REPORT_REJECT_STAGE: "Waiting for report",
  },
  AUDIT_TYPE_ARRAY: {
    VERIFICATION: "Verification",
    CERTIFICATION: "Certification",
  },
  DOCUMENT_SING_ARRAY: {
    DOCUSIGN: "Docusign",
    SELF: "Self",
    NO: "No",
  },
  VERIFICATION_STATUS_ARRAY: {
    1: "Agreement Signed",
    2: "Invoice Paid",
    3: "KP Updated",
    4: "Document Upload Completed",
    5: "Request Audit Date",
    6: "Audit date booked in",
    7: "Audit commenced",
    8: "Report finalized by provider",
    9: "Report submitted to NDIA",
  },
  VERIFICATION_STATUS_LOG: {
    1: "SLASIGNED",
    2: "INVOICE_PAID",
    3: "KEP_UPDATE",
    4: "DOCUMENT",
    5: "REQUEST_AUDIT",
    6: "AUDIT_DATE_BOOK",
    7: "PROGRESS",
    8: "ACCEPT_REPORT",
    9: "AU_GOVERNMENT",
  },

  CERTIFICATION_STATUS_ARRAY: {
    1: "Agreement Signed",
    2: "Invoice Paid",
    3: "Document Upload Completed",
    4: "Request Stage 1 Audit Date",
    5: "Audit date booked in",
    6: "Stage 1 Completed",
    7: "Request Stage 2 Audit Date",
    8: "Audit date booked in",
    9: "Stage 2 Completed",
    10: "Report finalized by provider",
    11: "Report submitted to NDIA",
  },
  CERTIFICATION_STATUS_LOG: {
    1: "SLASIGNED",
    2: "INVOICE_PAID",
    3: "DOCUMENT",
    4: "REQUEST_AUDIT",
    5: "AUDIT_DATE_BOOK",
    6: "ACCEPT_REPORT",
    7: "REQUEST_STAGE",
    8: "STAGE_CONFORM",
    9: "STAGE_COMPLETED",
    10: "ACCEPT_REPORT_STAGE",
    11: "AU_GOVERNMENT",
  },
};
