// eslint-disable-next-line import/no-anonymous-default-export
export default {
  isAuditorAuth: false,
  isSubmitting: false,
  isFetching: false,
  userAuditorInfo: {},
  setting: {},
  homePageData: {},
  pageData: {},
  userAuditorParams: {},
  faqData: [],
  isData: false,
  isHead: {},
  pagination: {},
  toaster: {
    open: false,
    message: "test",
    severity: "success",
  },
  dialogOpen: false,
  notificationAuditorCount: 0,
  notificationAuditorList: [],
  auditData: [],
  auditRequestData: {},
  otherDocumentData: [],
  chatInfo: [],
  preLoader: false,
  dashboardData: {},
  isViewType: {},
};
